### ISSUE TITLE
Server stops with no reason

### ISSUE THREAD

**Issue by LordRofl** [Didstopia/7dtd-server#1]
On startup the container kills itself for no reason. 
Here some lines from attached container:

app_update 294420 validate
 Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
 Update state (0x5) validating, progress: 2.73 (77928859 / 2857138631)
 Update state (0x5) validating, progress: 34.99 (999697391 / 2857138631)
 Update state (0x5) validating, progress: 67.64 (1932687233 / 2857138631)
 Update state (0x5) validating, progress: 93.93 (2683711401 / 2857138631)
Success! App '294420' fully installed.
quit
Starting 7 Days to Die..
Found path: /steamcmd/7dtd/7DaysToDieServer.x86_64
Mono path[0] = '/steamcmd/7dtd/7DaysToDieServer_Data/Managed'
Mono path[1] = '/steamcmd/7dtd/7DaysToDieServer_Data/Mono'
Mono config path = '/steamcmd/7dtd/7DaysToDieServer_Data/Mono/etc'
astra4642:~#

thats all, container gone :/

Hope you can help me

**Comment by Dids** [comment]
Did it work for you previously? If not, could you paste your Docker run command?

**Comment by Dids** [comment]
Never mind, I'm seeing this too, investigating.

**Comment by Dids** [comment]
The image has been fixed, but it won't automatically fix your current server config XML.

You can either install a fresh server and it let it copy a fresh XML, or you can take a look at the commit above, and change the single line in the XML to match the new format.

**Comment by LordRofl** [comment]
I´m using it since yesterday, so i can't say if it worked before. But you find a solution, very nice! Thank you :)

**Comment by Dids** [comment]
No problem! If anything else comes up, let me know. :)

**Comment by LordRofl** [comment]
I also use your rust-server image. It's great 👍  is it possible that you extend this image like the rust one?

**Comment by Dids** [comment]
Ah, awesome, that's great to hear! What did you have in mind? What is this missing? :)

**Comment by LordRofl** [comment]
Oh there is one thing now i run into: Can you add a variable that steamcmd not try to validate/update the server because we modify the standard files in config folder and everytime the server starts it gets overwritten :/

**Comment by Dids** [comment]
Oh sure thing, so the same as the "start mode" in Rust? Could you open a new issue about this feature, mainly just as a reminder for me? :)

**Comment by LordRofl** [comment]
Yes exactly  👍  :)
