### ISSUE TITLE
Sharing Violations - backup options for .ttp files

### ISSUE THREAD

**Issue by JyeGuru** [Didstopia/7dtd-server#11]
For some reason (likely completely unrelated to the fact I'm using your Docker container) the 7DTD server will randomly spam Sharing Violations when attempting to save the `.map` and `.ttp` files for connected players. Usually this is not an issue - on the next autosave (or `sa`) it flushes them to disk and it's ok. I just chalk this up to "It's Early Access, there are bugs."

However, it would be nice if there was a "save last X ttp files" option within this image. I am considering writing a script for it tonight, but it obviously wouldn't persist after a container reprovision. I also can't be the only person experiencing random player data resets at times when the server derps out.

Suggest: Compare hashes for last `.ttp` and `.ttp.bak` files with last manual backup, if changes, timestamp them and copy out. Then remove oldest X backups per user. If I get a chance to put this into a scheduler-style script tonight I'll put it through as a PR.

**Comment by Dids** [comment]
Are you still seeing these? As far as I know, this has been a longstanding Unity bug, but might've been fixed now.

**Comment by JyeGuru** [comment]
Honestly I haven't run up a server in quite some time. This can probably be closed since there have been no other reports of it. 👍

**Comment by Dids** [comment]
No worries, thanks for replying!
