### ISSUE TITLE
Unable to start server - Start.sh Aborted

### ISSUE THREAD

**Issue by jrohnerx** [Didstopia/7dtd-server#13]
Using Docker within unRAID (v. 6.4.0_rc16b). 
Steps: 
1) Created Docker container with ENV VAR "SEVEN_DAYS_TO_DIE_SERVER_STARTUP_ARGUMENTS" set to "-configfile=server_data/serverconfig.xml -logfile /dev/stdout -quit -batchmode -nographics -dedicated"
2) Set mount folder
3) Starting docker downloaded all files to mounted folder
4) Fails/stops with attached log.
[7dtd_error.log](https://github.com/Didstopia/7dtd-server/files/1588269/7dtd_error.log)

In the logs it references "Got a SIGSEGV while executing native code. This usually indicates a fatal error in the mono runtime or one of the native libraries used by your application." Not sure if this is the issue or not. 

Any clue what I'm doing wrong? 
All help is appreciated - thanks!

**Comment by Dids** [comment]
Steam requires 32-bit support, which means that the host system also needs to have a 32-bit compatibility layer, which unRAID doesn't seem to have _by default_.

You can, however, enable 32-bit support yourself:
https://lime-technology.com/forums/topic/58173-enable-ia32-to-support-dockers-that-require-32-bit-kernel-emulation/?tab=comments#comment-572083

This is unrelated to this Docker image, so I'm closing the issue.
