### ISSUE TITLE
Question about theforest dedicated server with docker

### ISSUE THREAD

**Issue by jammsen** [Didstopia/7dtd-server#22]
Hey @Dids im trying to dockerize "The Forest Dedicated Server" i got basically everything around the server running, but the server will only start in a VM or a LXC container right but not in a docker container, it bascially hangs itself. Did you already try out to make a TFDS on docker?
(Im using Wine and Winbind)

If you are interessted, maybe we could work together with @guntram on that, like we did on this 7dtd-server together. I could create a repository with what i have so far, but its not really working, so im not that comfortable to upload to github something thats not running.

Sorry for miss using the ticket system, but i didnt know how to get in touch with you otherwhise.

Regards,
jammsen and @guntram

**Comment by Dids** [comment]
Well over a year late, but assuming you got this to work eventually?

If not, I recently managed to get it working here: https://github.com/Didstopia/theforest-server

**Comment by jammsen** [comment]
Hey @Dids 
thanks for reaching out, i pretty much forgot about the ticket here, im so sorry. 
Yeah i got i working pretty early on, but i would always run into a glitch inside in the game, where first the small crafted stuff, then the big crafted stuff and then players would stop to be appear. All you could do is to restart the server and they were back again appearing and like after 30mins to 4 hours it would be again nothing to see for like 8 players connected. I tried different builds with other linux distros, more or less wine-hq tricks or different wine version (beta/stable), but the problem would always persist after time. I dont know if thats a windows to linux bug or the game itself or so, i didnt get any response on tickets for this bug other than, "its a windows game, so stop trying to do that id*ot", so eventually i stopped trying because no one wants to play on a server like that and the easy way out was to host on windows it seems. 

I see here and there a few servers popping up on the server browser called "jammsen-docker-generated" as title, because its the config example title :)

Did you have to fight with stuff like that too?
Congrats on getting it working!
