### ISSUE TITLE
Security Issue - Run with restricted user, not root.

### ISSUE THREAD

**Issue by stopspazzing** [Didstopia/7dtd-server#25]
While it is easier to run the game server as root, can you integrate a way to create a user named 7dtd, steamcmd or something with restricted permissions?

More information as to why it's a bad idea:
https://americanexpress.io/do-not-run-dockerized-applications-as-root/

**Comment by vinanrra** [comment]
Yes, it will be better to run as user:

ENV PGID 1000
ENV PUID 1000

**Comment by vinanrra** [comment]
Here is my aproach to fix this problem:

https://github.com/vinanrra/Docker-7DaysToDie/blob/test/user.sh

**Comment by Dids** [comment]
This was fixed with the latest commit (https://github.com/Didstopia/7dtd-server/commit/e79130245da8298b19f224a859f86d0eeae60c47), thanks to the base images already providing non-root user functionality.
