### ISSUE TITLE
ERROR: Default server configuration file not found, are you sure the server is up to date?

### ISSUE THREAD

**Issue by nj-io** [Didstopia/7dtd-server#37]
running the docker image with and without mounting the volumes recommended in the readme produces the same error, could I get some help?

With mounting
```
docker run -it --mount src=$(pwd)/serverFiles,dst=/steamcmd/7dtd,type=bind didstopia/7dtd-server
```

Without mounting
```
docker run didstopia/7dtd-server
```

**Comment by Dids** [comment]
There's a high chance that the image you're using is just outdated, so please try these steps first.

First try pulling the latest image: `docker pull didstopia/7dtd-server:latest`.
Next try running using the latest image: `docker run ... didstopia/7dtd-server:latest`.

**Comment by Rohaq** [comment]
Seeing the same issue here, definitely pulled the latest image, too.
