### ISSUE TITLE
Instructions on how to create and start this docker image?

### ISSUE THREAD

**Issue by jonneymendoza** [Didstopia/7dtd-server#42]
Hi.

Apologize for the question here but how exactly do you start this docker image and how to specify the optional arguments?

i entered the following:

```
sudo docker pull didstopia/7dtd-server
sudo docker create didstopia/7dtd-server
```

And i get the following error:

```Unable to find image 'didstopia/7dtd-server:latest' locally
Error response from daemon: pull access denied for didstopia/7ttd-server, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
```

If i do `sudo docker image ls` i see the image installed:

```
REPOSITORY              TAG       IMAGE ID       CREATED       SIZE
didstopia/7dtd-server   latest    b4c2193d90a4   6 days ago    1.34GB
hello-world             latest    feb5d9fea6a5   10 days ago   13.3kB
```
Sorry for the beginner question. 

edit doh i wrote the docker create command wrong.

How do you add the arguments?

**Comment by Dids** [comment]
The error mentions `7ttd`, are you sure it's not just a typo?

**Comment by jonneymendoza** [comment]
Hi there. yes it was a typo!

Thanks. I do have another query.

I tried to start the server but i dont think it is working as i am unable to connect to it using both my external public ip and my local LAN IP.

```2021-10-04T16:48:46 40.927 ERR Could not get country code: Error: ConnectFailure (The requested address is not valid in this context)                                                       2021-10-04T16:48:46 40.931 ERR   at System.Net.HttpWebRequest.EndGetResponse (System.IAsyncResult asyncResult) [0x00058] in <ae22a4e8f83c41d69684ae7f557133d9>:0                              at System.Net.WebClient.GetWebResponse (System.Net.WebRequest request, System.IAsyncResult result) [0x00000] in <ae22a4e8f83c41d69684ae7f557133d9>:0                                        at System.Net.WebClient.DownloadBitsResponseCallback (System.IAsyncResult result) [0x00015] in <ae22a4e8f83c41d69684ae7f557133d9>:0                                                       [S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.                                                                                                                      Setting breakpad minidump AppID = 251570                                                                                                                                                    2021-10-04T16:48:46 41.039 INF StartGame done                                                                                                                                               2021-10-04T16:48:46 41.041 INF [Steamworks.NET] GameServer.Init successful                                                                                                                  2021-10-04T16:48:46 41.044 INF [Steamworks.NET] Making server public                                                                                                                        2021-10-04T16:48:46 41.395 INF [Steamworks.NET] GameServer.LogOn successful, SteamID=90151785610047489, public IP=12*.4*.11*.11* ```

Also, how do i change the server details like the name?
