### ISSUE TITLE
ServerConfig files keeps being reset?

### ISSUE THREAD

**Issue by jonneymendoza** [Didstopia/7dtd-server#43]
Hi, everytime i edit the serverconfig.xml file and re-run the docker image using the below:

```
docker run --name 7dtd -d -t \
        -p 26900-26905:26900-26905/tcp \
        -p 26900-26905:26900-26905/udp \
        -e SEVEN_DAYS_TO_DIE_UPDATE_CHECKING="1" \
        -e SEVEN_DAYS_TO_DIE_CONFIG_FILE="/home/7dtd/server/serverconfig.xml" \
        -e SEVEN_DAYS_TO_DIE_BRANCH="latest_experimental" \
        --restart unless-stopped \
        -v /home/7dtd/server:/steamcmd/7dtd \
        -v /home/7dtd/data:/root/.local/share/7DaysToDie \
        didstopia/7dtd-server```


        
It resets my serverconfig file to default?

Is there a way to stop this from happening?

**Comment by jonneymendoza** [comment]
Edit: i added `-e SEVEN_DAYS_TO_DIE_CONFIG_FILE="/home/7dtd/server/serverconfigreal.xml" \`  and when it tried to run the server, it says it cannot find the file despite me having it there.

But its there!! I can even invoke `sudo nano : /home/7dtd/server/serverconfigreal.xml` and i am able to see the contents of that file


```
2021-10-06T16:59:53 0.251 INF Command line arguments: /steamcmd/7dtd/7DaysToDieServer.x86_64 -quit -batchmode -nographics -dedicated -configfile=/home/7dtd/server/serverconfigreal.xml
2021-10-06T16:59:53 0.263 ERR ====================================================================================================
2021-10-06T16:59:53 0.263 ERR Specified configfile not found: /home/7dtd/server/serverconfigreal.xml
2021-10-06T16:59:53 0.263 ERR ====================================================================================================```

**Comment by Dids** [comment]
You're not persisting the directory (`/home/7dtd/server`), that's probably why.

You should also always use `didstopia/7dtd-server:latest` as the `latest` tag ensures that you're not using an old version of the image.

Lastly, see the [readme](https://github.com/Didstopia/7dtd-server/blob/master/README.md) for the default paths, as they have changed over time, so you might also be using old paths.

**Comment by jonneymendoza** [comment]
> You're not persisting the directory (`/home/7dtd/server`), that's probably why.
> 
> You should also always use `didstopia/7dtd-server:latest` as the `latest` tag ensures that you're not using an old version of the image.
> 
> Lastly, see the [readme](https://github.com/Didstopia/7dtd-server/blob/master/README.md) for the default paths, as they have changed over time, so you might also be using old paths.

It wasnt explicitely mentioned in the readme here that you had to basically create another -v mounting point. That should have been specified
