### ISSUE TITLE
Problem with fork

### ISSUE THREAD

**Issue by jammsen** [Didstopia/7dtd-server#5]
I tried the fork:
https://github.com/jaredballou/7dtd-server/commit/9fcb06c2f7cb5ab976b4d1c5eef2df52d5c75eb8
https://hub.docker.com/r/jballou/7dtd-server/

There is an error and i commented on the commit, https://github.com/jaredballou/7dtd-server/commit/9fcb06c2f7cb5ab976b4d1c5eef2df52d5c75eb8#commitcomment-21871251

Do you got any info on this project?
Do you plan on update yours?

**Comment by Dids** [comment]
@jammsen Sure thing, I'll let you know once it's fixed. :)
